---
name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  HUGO_VERSION: "0.110.0"
  S3DEPLOY_VERSION: "2.9.0"
  CURL_CACHE_DIR: "~/.cache/curl"

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Cache curl downloads
        uses: actions/cache@v3
        with:
          path: ${{env.CURL_CACHE_DIR}}
          key: "${{runner.os}}-curl-s3deploy-${{env.S3DEPLOY_VERSION}}"

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{env.HUGO_VERSION}}

      - name: Setup s3deploy
        shell: bash
        run: |
          mkdir -p "${{env.CURL_CACHE_DIR}}"
          S3DEPLOY_TARBALL="s3deploy_${{env.S3DEPLOY_VERSION}}_linux-amd64.tar.gz"
          curl -s --output "${{env.CURL_CACHE_DIR}}/${S3DEPLOY_TARBALL}" \
            --time-cond "${{env.CURL_CACHE_DIR}}/${S3DEPLOY_TARBALL}" \
            --location \
            "https://github.com/bep/s3deploy/releases/download/v${{env.S3DEPLOY_VERSION}}/${S3DEPLOY_TARBALL}"
          tree "${{env.CURL_CACHE_DIR}}"
          tar -xvf "${{env.CURL_CACHE_DIR}}/${S3DEPLOY_TARBALL}" s3deploy
          chmod +x ./s3deploy

      - name: Build
        run: hugo --minify

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{secrets.AWS_IAM_ROLE}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Run s3deploy
        shell: bash
        env:
          S3_BUCKET: ${{secrets.AWS_S3_BUCKET}}
          AWS_REGION: ${{secrets.AWS_REGION}}
          CLOUDFRONT_DISTRIBUTION: ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION}}
        run: |
          ./s3deploy -acl public -distribution-id "${CLOUDFRONT_DISTRIBUTION}" \
          -source "./public/" -bucket "${S3_BUCKET}" -region "${AWS_REGION}"
